name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache test data
      uses: actions/cache@v4
      with:
        path: tests/e2e/.test_data_cache
        key: test-data-${{ hashFiles('tests/e2e/test_split_performance.py', 'tests/e2e/test_metrics_store_performance.py') }}
        restore-keys: |
          test-data-
    
    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        pip install tox
        
    - name: Run tests with tox
      run: tox -e py${{ matrix.python-version }}
      
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        pip install tox
        
    - name: Run linting
      run: tox -e lint